name: Trigger auto deployment for container-app-sfgtg4rui22o4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-sfgtg4rui22o4-AutoDeployTrigger-3dfa0376-6462-43b6-816a-c1ef8abe48fa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPSFGTG4RUI22O4_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPSFGTG4RUI22O4_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPSFGTG4RUI22O4_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPSFGTG4RUI22O4_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPSFGTG4RUI22O4_REGISTRY_PASSWORD }}
          containerAppName: container-app-sfgtg4rui22o4
          resourceGroup: appspacesragappb7fda492
          imageToBuild: default/container-app-sfgtg4rui22o4:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


